# This workflow will deploy WordPress on Azure Container Apps
name: WordPress Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64
          chmod +x ./bicep
          sudo mv ./bicep /usr/local/bin/bicep
      - name: Run Bicep linter
        run: bicep build ./main.bicep

  validate:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Validate Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./main.bicep
          parameters: location=${{ secrets.AZURE_LOCATION }} prefix=${{ secrets.AZURE_PREFIX }} tags=${{ secrets.AZURE_TAGS }} appName=${{ secrets.AZURE_APP_NAME }}
          deploymentMode: Validation

  deploy:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          scope: resourcegroup
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RESOURCE_GROUP }}
          template: ./main.bicep
          parameters: location=${{ secrets.AZURE_LOCATION }} prefix=${{ secrets.AZURE_PREFIX }} tags=${{ secrets.AZURE_TAGS }} appName=${{ secrets.AZURE_APP_NAME }}
          deploymentMode: Incremental

